import { useState } from 'react'
import Header from './components/Header'
import Arrow from './components/Arrow'
import Services from './components/Services'
import { companyEmail, questions } from './content'

export default function App() {
  const [interest, setInterest] = useState('General operations support')
  return <>
    <a className="skip-link" href="#main">Skip to content</a><Header />
    <main id="main">
      <section id="home" className="hero"><div className="wrap hero-layout">
        <div className="hero-copy"><p className="section-label"><span className="label-line" />Practical support. Philippine businesses.</p><h1>A clearer way<br />to run the<br /><em>everyday.</em></h1><p className="hero-description">Your business has a lot of moving parts.<br className="desktop-break" /> We help you bring the numbers, people, and processes together.</p><div className="hero-actions"><a className="button" href="#contact">Let’s talk about your business <Arrow diagonal /></a><a className="quiet-link" href="#services">Find the support you need</a></div></div>
        <div className="hero-art"><div className="art-heading"><span>The business behind your business.</span><span className="art-cross" aria-hidden="true">+</span></div><div className="work-sheet"><div className="sheet-top"><span>A little clarity goes a long way.</span><span className="sheet-mark" aria-hidden="true">R.</span></div><div className="sheet-title">From moving parts.<br /><em>To a way forward.</em></div><div className="sheet-row"><span className="sheet-check" aria-hidden="true">✓</span><span>The numbers, understood.</span></div><div className="sheet-row"><span className="sheet-check" aria-hidden="true">✓</span><span>The next step, clear.</span></div><div className="sheet-row"><span className="sheet-check" aria-hidden="true">✓</span><span>The team, on the same page.</span></div><div className="sheet-bottom"><span>Accounting · Operations · Software</span><span aria-hidden="true">↗</span></div></div><div className="art-bottom"><span>Built around the work you actually do.</span><svg width="62" height="45" viewBox="0 0 62 45" fill="none" aria-hidden="true"><path d="M2 43 23 22l12 12L59 3M39 3h20v20" stroke="currentColor" strokeWidth="2" /></svg></div></div>
      </div><div className="hero-foot wrap"><p><span className="small-seal" aria-hidden="true">R</span>Grounded in accounting experience <strong>since 2004.</strong></p><a href="#services">A good place to begin <span aria-hidden="true">↓</span></a></div></section>
      <Services onInterest={setInterest} />
      <section id="about" className="about-section"><div className="wrap about-layout"><div className="about-origin"><p className="section-label">Our foundation</p><span className="origin-year">2004<span className="origin-dot">.</span></span><p>Our accounting experience<br />starts here.</p></div><div className="about-copy"><p className="section-label">Why Ridgewell</p><h2>We see the business<br />behind the numbers.</h2><p>Accounting gives you a close view of how a business really works. That perspective shapes the way we support your operations today.</p><p>We look at the routines, handoffs, and decisions around the numbers. Then we help you find an improvement that fits your people, your time, and your resources.</p><a href="#approach" className="text-link light-link">How we approach the work <Arrow /></a></div></div></section>
      <section id="approach" className="approach-section section-space"><div className="wrap approach-layout"><div className="approach-intro"><p className="section-label">A practical way forward</p><h2>Start small.<br />Make it useful.<br /><em>Build from there.</em></h2><p>You don’t need a finished plan. Bring the process that is taking too long, or the question you keep coming back to.</p><a className="text-link" href="#contact">Tell us what needs attention <Arrow /></a></div><div className="approach-steps"><article><span className="step-number">01</span><div><h3>Understand the everyday.</h3><p>Look at how work happens now. Identify the recurring task, missed handoff, or unclear responsibility that needs attention.</p></div></article><article><span className="step-number">02</span><div><h3>Find the useful change.</h3><p>Work out what will help: a clearer process, practical documentation, accounting support, or a tool that fits.</p></div></article><article><span className="step-number">03</span><div><h3>Put it to work.</h3><p>Turn the next step into something your team can use, with support to refine it as your business changes.</p></div></article></div></div></section>
      <section id="questions" className="questions-section"><div className="wrap questions-layout"><div><p className="section-label">Before we talk</p><h2>A few good<br />questions.</h2></div><div className="questions-list">{questions.map(item => <details key={item.question}><summary>{item.question}<span className="disclosure-icon" aria-hidden="true" /></summary><p>{item.answer}</p></details>)}</div></div></section>
      <section id="contact" className="contact-section section-space"><div className="wrap contact-layout"><div><p className="section-label">A useful next conversation</p><h2>What could work<br /><em>a little better?</em></h2><p>Tell us about the part of your business that needs attention. A clear question is enough to start.</p><a className="text-link" href={`mailto:${companyEmail}`}>Email Ridgewell directly <Arrow diagonal /></a></div><div className="contact-placeholder"><p className="section-label">Your starting point</p><h3>{interest}</h3><p>Share a little about your business and what you would like to improve.</p><a className="button" href={`mailto:${companyEmail}?subject=${encodeURIComponent(`Inquiry: ${interest}`)}`}>Open your email app <Arrow diagonal /></a></div></div></section>
    </main>
    <footer className="site-footer"><div className="wrap"><div className="footer-main"><a className="brand footer-brand" href="#home" aria-label="Ridgewell home"><img src="./brand/ridgewell-logo.jpg" width="1186" height="280" alt="Ridgewell Management Services, Inc." /></a><p>Good work deserves<br />a clearer way forward.</p><a className="text-link" href="#home">Back to top <span aria-hidden="true">↑</span></a></div><div className="footer-bottom"><span>© {new Date().getFullYear()} Ridgewell Management Services, Inc.</span><span>Accounting. Operations. Practical progress.</span><a href="#questions">Common questions</a></div></div></footer>
  </>
}
